---
- name: Deploy simple_solutions
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  tasks:
      - name: pull from git
        git:
          repo: git@github.com:BinhexSystemss/simple_solutions.git
          dest: /opt/odoo-server/extra_addons/binhex/simple_solutions
          update: yes
          version: "{{ branch }}"
      
      - name: Restart Odoo Service
        service: name=odoo state=restarted