---
- name: Deploy vertical-real-estate
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  tasks:
      - name: pull from git
        git:
          repo: git@github.com:BinhexTeam/alca_custom.git
          dest: /opt/odoo-server/extra_addons/binhex/alca_custom
          update: yes
          version: "{{ branch }}"
      
      - name: Restart Odoo Service
        service: name=odoo state=restarted