---
- name: Deploy Binhex Odoo SAAS Ansible
  hosts: ANSIBLE-PROD
  become: true
  tasks:
      - name: pull from git
        git:
          repo: git@github.com:pdaucht/binhex-odoosaas.git
          dest: /root/binhex-odoosaas
          update: yes
          version: "{{ branch }}"