---
- name: Deploy Binhex-Deploy Ansible
  hosts: localhost
  tasks:
      - name: Pull Binhex-Deploy from GITHUB
        git:
          repo: git@github.com:pdaucht/binhex-deploy.git
          dest: /var/lib/jenkins/binhex-deploy
          update: yes
          version: master