---
- name: Deploy Binhex-Deploy Ansible
  hosts: localhost
  become: true
  tasks:
      - name: pull from git
        git:
          repo: git@github.com:pdaucht/binhex-deploy.git
          dest: /var/lib/jenkins/binhex-deploy
          update: yes
          version: master