---
- name: Deploy Odoo SAAS
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  tasks:
      - name: pull from git
        git:
          repo: https://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@github.com/BinhexSystemss/odoo_saas.git
          dest: /usr/lib/python3/dist-packages/odoo/extra-addons/binhex/odoo_saas
          update: yes
          version: "{{ branch }}"
      
      - name: Restart Odoo Service
        service: name=odoo state=restarted