---
- name: Update PV4205
  hosts: "{{ host }}"
  become: true
  gather_facts: false
  tasks:
      - name: pull from git
        git:
          repo: git@github.com:BinhexTeam/PV4205.git
          dest: /usr/lib/python3/dist-packages/odoo/extra-addons/binhex/PV4205
          update: yes
          version: "{{ branch }}"
      
      - name: Restart Odoo Service
        service: name=odoo state=restarted